### ISSUE TITLE
OW Mobile (iOS): no data

### ISSUE THREAD

**Issue by stmeister** [IOTA-NA/OW-Issues#2]
I installed the current version (v1.0b24) of the OW Mobile app and filled-in the "Account" screen. However it seems that nothing is getting downloaded. When pushing the "Update" Link on the tab "MyEvents" then the following appears (one by one):

Connecting to OW
Data Received
Event List count = 0

The list or screens remains empty.

Regards,
Stefan

**Comment by hpavlov** [comment]
Hi Stefan,

Do you still experience the same issue as I don't see a reason why it would be happening.

Please note that it may tame a minute or two for any new events you may have submitted stations for from OW Desktop to appear in OW Mobile.

Also note that OW Mobile only shows stations for asteroidal occultations where the user has announced their intentions to observe to everyone else i.e. it doesn't work for events added for 'Follow up'.

**Comment by stmeister** [comment]
Hi Hristo

I just tried it again and I still get the same result: an empty list.

Also I reentered my account details, as I was not sure, if the password was correct. BTW, there is no check or notice, if a wrong password will be entered.

The three messages (as listed above) appear within seconds and I have not one single event in the list. On the PC (with the same account details) there is currently a very large list of events active.

**Comment by hpavlov** [comment]
Hi Stefan,

I found an account under your name with an email address in dolphins.ch

I see that there are no stations registered on the server for this account. 

Can you please confirm that you have not added the events as 'Follow ups' but you have submitted a station using the 'Observer from ...' option in OW. The events need to show under 'My Events' in OW Desktop.

@jrgrismore: FYI, this seems to be a problem with stations not being registered on the Planner server rather than a problem with OW Mobile (iOS)

**Comment by stmeister** [comment]
Hi Hristo

Actually I have defined three stations in my OW desktop app (Configuration > General > My site > Sites), where "Sternwarte Bülach" is the main one. Do they also need to be defined elsewhere to be "active" on the server? On Configuration > Observation planner > Account Information everything seems to be correctly filled-in and valid.

Currently I have no planned events (neither Follow ups nor My Events). Probably that is the issue. I thought that the complete calculated list will be shown 1:1 in the Mobile app. Usually I only mark events as "My Events" on the same day they are happening and if I am really sure that I can observe and the weather conditions are good enough.

**Comment by hpavlov** [comment]
Hi Stefan,

OW Mobile only shows your 'My Events' at the moment. The Android version of the app shows a message explaining this when there are no events in the list (attached screenshot).

![image](https://user-images.githubusercontent.com/3581627/71518129-41fe7280-28a9-11ea-8498-fd077f02ef9e.png)

@jrgrismore may be you could do something similar in the iOS version.

**Comment by Esdert** [comment]
Hi, I have the same - Event List count = 0, with five “genuine” predictions in My Events list. (I didn’t even know that “follow up” existed :-) )
Esdert Edens

**Comment by jrgrismore** [comment]
If you have verified that you have announced events, the problem is very likely an incorrect or mistyped userid or password in OW Mobile (iOS).

John

**Comment by jrgrismore** [comment]
There are a few other improvements I’ll be adding to OW Mobile (iOS), so I’ll include this also.

John

**Comment by Esdert** [comment]
My password was correct! But ... Simplifying the password did the trick. Now it works.

**Comment by jrgrismore** [comment]
Glad you got it working.

John
