### ISSUE TITLE
Direction arrows on center line are missing

### ISSUE THREAD

**Issue by tedblank** [IOTA-NA/OW-Issues#7]
**Which software is this affecting and which version**
 - Software:  OW Desktop
 - Version: 4.7.0.2 and previous

**Describe the bug**
In the past I remember that on the green center line track there were small arrowheads showing the direction of movement of the asteroid shadow.  I don't see them anymore.  I was just wondering if it would be possible to bring them back?  Or perhaps I am just missing them somehow.  They were very small, but useful.

**Comment by hpavlov** [comment]
Fixed in OW v4.7.3
